### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by wangchunlin** [gasevi/pyreclab#27]
Could not find a version that satisfies the requirement pyreclab . My system is Windows 10 64 bit. Could you help me out?

**Comment by gasevi** [comment]
Hi @wangchunlin,

   pyreclab is not supported in Windows, that's why you don't find a wheel package for that system. A good alternative is to use pyreclab on Google Colaboratory. You just need to install it using pip writing the following command in a cell:

!pip install pyreclab

   thanks for using pyreclab!

Best,

GSV.
